# Generated by Django 6.0.6 on 2026-07-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('price', models.IntegerField(verbose_name='Narxi (som)')),
                ('ram', models.CharField(max_length=20, verbose_name='RAM')),
                ('storage', models.CharField(max_length=20, verbose_name='Xotira')),
                ('camera', models.CharField(blank=True, max_length=50, verbose_name='Kamera')),
                ('battery', models.CharField(blank=True, max_length=50, verbose_name='Batareya')),
                ('description', models.TextField(blank=True, verbose_name="Qoshimcha ma'lumot")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Telefon',
                'verbose_name_plural': 'Telefonlar',
                'ordering': ['price'],
            },
        ),
    ]
